name: Bug Report
description: File a bug report
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!


  - type: markdown
    attributes:
      value: |
          # Background
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you running?
      options:
        - Windows 10
        - Windows 11
        - macOS
        - Ubuntu 22.04
        - CentOS 7
        - Other Linux (please specify below)
    validations:
      required: true
  - type: input
    id: other-os
    attributes:
      label: Other Linux
      placeholder: e.g. Fedora 38
  - type: input
    id: version
    attributes:
      label: Workflow Version
      description: This is most easily found in the workflow output log
      placeholder: v1.2.3
    validations:
      required: true
  - type: dropdown
    id: execution
    attributes:
      label: Workflow Execution
      description: Where are you running the workflow?
      options:
        - EPI2ME Desktop (Local)
        - EPI2ME Desktop (Cloud)
        - Command line (Local)
        - Command line (Cluster)
        - Other (please describe)
    validations:
      required: true
  - type: input
    id: other-workflow-execution
    attributes:
      label: Other workflow execution
      description: If "Other", please describe
      placeholder: Tell us where / how you are running the workflow.

  - type: markdown
    attributes:
      value: |
        # EPI2ME Desktop Application
        If you are using the application please provide the following.
  - type: input
    id: labs-version
    attributes:
      label: EPI2ME Version
      description: Available from the application settings page.
      placeholder: v5.1.1
    validations:
      required: false


  - type: markdown
    attributes:
      value: |
        # Command-line execution
        If you are using nextflow on a command-line, please provide the following.
  - type: textarea
    id: cli-command
    attributes:
      label: CLI command run
      description: Please tell us the command you are running
      placeholder: e.g. nextflow run epi2me-labs/wf-human-variations -profile standard --fastq my-reads/fastq
    validations:
      required: false
  - type: dropdown
    id: profile
    attributes:
      label: Workflow Execution - CLI Execution Profile
      description: Which execution profile are you using? If you are using a custom profile or nextflow configuration, please give details below.
      options:
        - standard (default)
        - singularity
        - custom
    validations:
      required: false


  - type: markdown
    attributes:
      value: |
        # Report details
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: For CLI execution please include the full output from running nextflow. For execution from the EPI2ME application please copy the contents of the "Workflow logs" panel from the "Logs" tab corresponding to your workflow instance. (This will be automatically formatted into code, so no need for backticks).
      render: shell
    validations:
      required: true
  - type: textarea
    id: activity-log
    attributes:
      label: Application activity log entry
      description: For use with the EPI2ME application please see the Settings > View Activity Log page, and copy the contents of any items listed in red using the Copy to clipboard button.
      render: shell
    validations:
      required: false
  - type: dropdown
    id: run-demo
    attributes:
      label: Were you able to successfully run the latest version of the workflow with the demo data?
      description: For CLI execution, were you able to successfully run the workflow using the demo data available in the [Install and run](./README.md#install-and-run) section of the `README.md`? For execution in the EPI2ME application, were you able to successfully run the workflow via the "Use demo data" button?
      options:
        - 'yes'
        - 'no'
        - other (please describe below)
    validations:
      required: true
  - type: textarea
    id: demo-other
    attributes:
      label: Other demo data information
      render: shell
    validations:
      required: false

